version: 2

sources:
  - name: raw
    description: Raw WoW player activity logs from DuckDB database
    schema: main
    tables:
      - name: wowlogs
        description: WoW player activity event logs
        columns:
          - name: player_id
            description: Unique identifier for each player
          - name: guild
            description: Guild identifier (numeric)
          - name: level
            description: Character level at time of event
          - name: race
            description: Character race (e.g., Human, Orc)
          - name: class
            description: Character class (e.g., Warrior, Mage)
          - name: where
            description: Location where the event occurred
          - name: datetime
            description: Timestamp of the event
